-module(pasture_twitter).

%% Let this fail on whatever, it's being supervised.

-export([start_link/0]).

-behaviour(gen_server).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).

%% Debug
-export([
    %%generate_signature/4
]).

-define(SERVER, ?MODULE).
-define(STATE,pasture_twitter_state).
-record(?STATE,{
    oauth_consumer_key,
    oauth_consumer_secret,
    oauth_nonce, %% The value for this request was generated by base64 encoding 32 bytes of random data, and stripping out all non-word characters, but any approach which produces a relatively random alphanumeric string should be OK here.
    oauth_signature,
    oauth_signature_method = "HMAC-SHA1",
    oauth_timestamp, %% number of seconds since the Unix epoch
    oauth_token,
    oauth_token_secret,
    oauth_version = "1.1"
}).

start_link() ->
    {ok,Pid} = gen_server:start_link({local, ?SERVER}, ?MODULE, {}, []),
    io:format("Pasture twitter started ... ~p\n",[Pid]),
    {ok,Pid}.

init({}) ->
    {ok,CK} = application:get_env(pasture,oauth_consumer_key),
    {ok,CS} = application:get_env(pasture,oauth_consumer_secret),
    {ok,T} = application:get_env(pasture,oauth_token),
    {ok,TS} = application:get_env(pasture,oauth_token_secret),
    {ok, #?STATE{
        oauth_consumer_key = CK,
        oauth_consumer_secret = CS,
        oauth_token = T,
        oauth_token_secret = TS
    }}.

handle_call(update_status, _From, State) ->
    HttpMethod = "POST",
    Status = "Hello Ladies + Gentlemen, a signed OAuth request!",
    QString = "?include_entities=true",
    Timestamp = generate_timestamp(),
    NoOnce = base64:encode_to_string(crypto:rand_bytes(32))q,
    Params = [
        {"status","Hello Ladies + Gentlemen, a signed OAuth request!"},
        {"include_entities","true"},
        {"oauth_consumer_key",State#?STATE.oauth_consumer_key},
        {"oauth_nonce",NoOnce},
        {"oauth_signature_method",State#?STATE.oauth_signature_method},
        {"oauth_timestamp",Timestamp},
        {"oauth_token",State#?STATE.oauth_token},
        {"oauth_version",State#?STATE.oauth_version}
    ],
    URL = "https://api.twitter.com/1.1/statuses/update.json" ++ QString,
    Signature =
        oauth:hmac_sha1_signature(HttpMethod, URL, Params,
                                                {State#?STATE.oauth_consumer_key,
                                                  State#?STATE.oauth_consumer_secret,
                                                  hmac_sha1},
                                                State#?STATE.oauth_token_secret),
    %% io:format("Generated Signature : ~p\n\n",[Signature]),
    %% ibrowse:send_req(Url, Headers, ibrowse_method(HttpMethod), [], [{stream_to, self()}]).
    HeaderParams = [
        {"oauth_consumer_key",State#?STATE.oauth_consumer_key},
        {"oauth_nonce",NoOnce},
        {"oauth_signature_method",State#?STATE.oauth_signature_method},
        {"oauth_timestamp",Timestamp},
        {"oauth_token",State#?STATE.oauth_token},
        {"oauth_version",State#?STATE.oauth_version}
    ],
    AutorizationHeader = oauth:header(HeaderParams),
    Headers = [
        {"Authorization", AutorizationHeader},
        {"Content-Type", "application/x-www-form-urlencoded"}
    ],
    Body = "status=Hello%20Ladies%20%2b%20Gentlemen%2c%20a%20signed%20OAuth%20request%21",
    Resp = ibrowse:send_req(URL, Headers, ibrowse_method(HttpMethod), Body),
    io:format("HTTP RESPONSE:\n~p\n",[Resp]),
    {reply,ok,State}.

handle_cast(_Msg, State) ->
    {noreply, State}.

handle_info(_Info, State) ->
    {noreply, State}.

terminate(_Reason, _State) ->
    ok.

code_change(_OldVsn, State, _Extra) ->
    {ok, State}.

%% ----

% Example Post:

% POST /1/statuses/update.json?include_entities=true HTTP/1.1
% Accept: */*
% Connection: close
% User-Agent: OAuth gem v0.4.4
% Content-Type: application/x-www-form-urlencoded
% Authorization:
%         OAuth oauth_consumer_key="xvz1evFS4wEEPTGEFPHBog",
%               oauth_nonce="kYjzVBB8Y0ZFabxSWbWovY3uYSQ2pTgmZeNu2VS4cg",
%               oauth_signature="tnnArxj06cWHq44gCs1OSKk%2FjLY%3D",            -                          <- Generated
%               oauth_signature_method="HMAC-SHA1",
%               oauth_timestamp="1318622958",                            -                     -                          <- Generated
%               oauth_token="370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb",
%               oauth_version="1.0"
% Content-Length: 76
% Host: api.twitter.com

% status=Hello%20Ladies%20%2b%20Gentlemen%2c%20a%20signed%20OAuth%20request%21

ibrowse_method("POST") ->
    post;
ibrowse_method("GET") ->
    get.


generate_timestamp() ->
    calendar:datetime_to_gregorian_seconds({{1970,1,1}, {0,0,0}}) -
        calendar:datetime_to_gregorian_seconds({date(),time()}).